### PR TITLE
Cnpm fix

### PR DESCRIPTION
**Pull request by renaesop**
By treating symlink as a type of alias, the cnpm/pnpm issue can be resolved.
#5

### CODE REVIEW

**Comment by developit** [comment]
LGTM!

**Comment by fengmk2** [comment]
@developit can you publish a new version to npm?

**Comment by developit** [comment]
@fengmk2 Yup, just published: `modify-babel-preset@3.2.0`.

**Comment by fengmk2** [comment]
@developit Thanks!

**Pull request merged**
